redis-config:
  url: 127.0.0.1:6379
  db: 0
  password: Chenzhou@308
  rdb_path: ./dump.rdb
  redis_bin: redis-server
  conf_path: ./conf/redis/redis.conf

tendermint-config:
  url: 127.0.0.1:26657

ipfs-config:
  url: 116.62.48.146:5001

http-server-config:
  run_mode : release
  port : 30001
  read_timeout : 6000
  write_timeout : 6000

rpc-config:
  port : 40001
