package code

const (
	CodeTypeOK = iota
	CodeTypeInvalidSign
	CodeTypeInvalidValidator
	CodeTypeEncodingError
	CodeTypeRedimintQueryError
	CodeTypeRedimintExecuteError
	CodeTypeTxExeCommitError
	CodeTypeTxExeSyncError
	CodeTypeGetChainInfoError
	CodeTypeInvalidExecuteMode
	CodeTypeInvalidRedisCommand
	CodeTypeInvalidTx
	CodeTypePermissionDenied
	CodeTypeDBPasswordIncorrectError
	CodeTypeTokenTimeoutError
	CodeTypeTokenInvalidError
	CodeTypeIncorrectPassword
	CodeTypeInternalError
	CodeTypeGetChainGenesisError
)
